- set_fact:
    temp_dir: /tmp

- name: Download etcd package
  uri:
    url: https://github.com/etcd-io/etcd/releases/download/v3.4.0/etcd-v3.4.0-linux-amd64.tar.gz
    dest: "{{ temp_dir }}/etcd-v3.4.0-linux-amd64.tar.gz"
    status_code: [200, 304]

- name: Clean up past runs
  file:
    name: "{{ temp_dir }}/etcd-v3.4.0-linux-amd64"
    state: absent
  become: yes

- name: Extract etcd package
  unarchive:
    src: "{{ temp_dir }}/etcd-v3.4.0-linux-amd64.tar.gz"
    dest: "{{ temp_dir }}/"
    remote_src: yes

- name: Move etcd binary to executable path
  shell:
    cmd: mv etcd-v3.4.0-linux-amd64/etcd* /usr/local/bin/
    chdir: "{{ temp_dir }}"
  become: yes

- name: Create etcd directories
  file:
    name: "{{ item }}"
    state: directory
  loop:
    - /etc/etcd
    - /var/lib/etcd
  become: yes

- name: Copy CA to etcd directory
  copy:
    src: "{{ WORK_DIR }}/{{ item }}"
    dest: "/etc/etcd/"
  loop:
    - ca.pem
    - kubernetes-key.pem
    - kubernetes.pem
  become: yes

- name: Create etcd systemd unit
  template:
    src: "../templates/etcd.service.j2"
    dest: "/etc/systemd/system/etcd.service"
  vars:
    etcd_cluster_string: "{{
      groups['controllers'] |
      map('extract', hostvars , 'cluster_ip') |
      map('regex_replace', '(.+)' , 'https://\\1:2380') |
      list |
      join(',')
    }}"
  become: yes

- name: Start etcd server
  systemd:
    name: etcd
    state: started
    enabled: yes
    daemon_reload: yes
  become: yes
