---
- block:
    - set_fact:
        file_path: "{{ WORK_DIR }}/{{ item.name }}.kubeconfig"

    - name: Check if {{ item.name }}.kubeconfig already exists
      stat:
        path: "{{ file_path }}"
      register: results

    - block:
        - name: Set cluster for {{ item.name }}
          shell:
            cmd: |
              kubectl config set-cluster kubernetes-the-hard-way \
                --certificate-authority=ca.pem \
                --embed-certs=true \
                --server=https://{{ item.server_ip | default("127.0.0.1") }}:6443 \
                --kubeconfig={{ item.name }}.kubeconfig
            chdir: "{{ WORK_DIR }}"

        - name: Set credentials for {{ item.name }}
          shell:
            cmd: |
              kubectl config set-credentials {{ item.kube_cfg_user }} \
                --client-certificate={{ item.name }}.pem \
                --client-key={{ item.name }}-key.pem \
                --embed-certs=true \
                --kubeconfig={{ item.name }}.kubeconfig
            chdir: "{{ WORK_DIR }}"

        - name: Set context for {{ item.name }}
          shell:
            cmd: |
              kubectl config set-context default \
                --cluster=kubernetes-the-hard-way \
                --user={{ item.kube_cfg_user }} \
                --kubeconfig={{ item.name }}.kubeconfig
            chdir: "{{ WORK_DIR }}"

        - name: Use context for {{ item.name }}
          shell:
            cmd: |
              kubectl config use-context default --kubeconfig={{ item.name }}.kubeconfig
            chdir: "{{ WORK_DIR }}"

      when: results.stat.exists == False

  delegate_to: localhost