---
- set_fact:
    kubeconfig_clients:
    - {name: kube-controller-manager, kube_cfg_user: "system:kube-controller-manager"}
    - {name: kube-scheduler, kube_cfg_user: "system:kube-scheduler"}
    - {name: admin, kube_cfg_user: "admin"}

- set_fact:
    kubeconfig_clients: "{{ \
      kubeconfig_clients + \
      [{name: item, kube_cfg_user: \"system:node:\" + item}] \
    }}"
  loop: "{{ groups['workers'] }}"

- include_tasks: kubeconfig-generate-generic.yaml
  loop: "{{ kubeconfig_clients }}"
