---
- name: Download CNI plugins package
  uri:
    url: https://github.com/containernetworking/plugins/releases/download/v0.8.2/cni-plugins-linux-amd64-v0.8.2.tgz
    dest: "{{ WORK_DIR }}/cni-plugins-linux-amd64-v0.8.2.tgz"
    status_code: [200, 304]

- name: Clean up past runs
  file:
    name: "/opt/cni/bin/"
    state: absent
  become: yes

- name: Create CNI plugin directory
  file:
    name: "/opt/cni/bin/"
    state: directory
  become: yes

- name: Extract CNI plugin package
  unarchive:
    src: "{{ WORK_DIR }}/cni-plugins-linux-amd64-v0.8.2.tgz"
    dest: "/opt/cni/bin/"
    remote_src: yes
  become: yes

# Configure CNI networking
- name: Create CNI conf directory
  file:
    name: "/etc/cni/net.d/"
    state: directory
  become: yes

- name: Create the loopback network configuration file
  copy:
    content: |
      {
          "cniVersion": "0.3.1",
          "name": "lo",
          "type": "loopback"
      }
    dest: /etc/cni/net.d/99-loopback.conf
  become: yes