---
- set_fact:
    service_name: "{{ item }}"
    service_binary_url: "{{ K8S_RELEASE_BASE_URL }}/{{ item }}"

- name: Download {{ service_name }} binary
  uri:
    url: "{{ service_binary_url }}"
    dest: /usr/local/bin/
    mode: "755"
    status_code: [200, 304]
  become: yes

- name: Create systemd unit for {{ service_name }}
  copy:
    src: "{{ WORK_DIR }}/{{ service_name }}.service"
    dest: "/etc/systemd/system/{{ service_name }}.service"
  become: yes

- name: Start {{ service_name }} server
  systemd:
    name: "{{ service_name }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  become: yes
