---
- block:
    - name: Set cluster for {{ name }}
      shell:
        cmd: |
          kubectl config set-cluster kubernetes-the-hard-way \
            --certificate-authority=ca.pem \
            --embed-certs=true \
            --server=https://{{ server_ip | default("127.0.0.1") }}:6443 \
            --kubeconfig={{ name }}.kubeconfig
        chdir: "{{ WORK_DIR }}"

    - name: Set credentials for {{ name }}
      shell:
        cmd: |
          kubectl config set-credentials {{ kube_cfg_user }} \
            --client-certificate={{ name }}.pem \
            --client-key={{ name }}-key.pem \
            --embed-certs=true \
            --kubeconfig={{ name }}.kubeconfig
        chdir: "{{ WORK_DIR }}"

    - name: Set context for {{ name }}
      shell:
        cmd: |
          kubectl config set-context default \
            --cluster=kubernetes-the-hard-way \
            --user={{ kube_cfg_user }} \
            --kubeconfig={{ name }}.kubeconfig
        chdir: "{{ WORK_DIR }}"

    - name: Use context for {{ name }}
      shell:
        cmd: |
          kubectl config use-context default --kubeconfig={{ name }}.kubeconfig
        chdir: "{{ WORK_DIR }}"

  delegate_to: localhost