- set_fact:
    temp_dir: /tmp

- name: Download Kube Router manifest template
  uri:
    url: https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/generic-kuberouter-all-features.yaml
    dest: "{{ temp_dir }}/generic-kuberouter-all-features.yaml"
    status_code: [200, 304]

- name: Create Kube Router manifest for this deployment
  replace:
    path: "{{ temp_dir }}/generic-kuberouter-all-features.yaml"
    regexp: "{{ item.search }}"
    replace: "{{ item.replace }}"
  loop:
    - {search: "%APISERVER%", replace: "https://{{ API_SERVER_IP }}:6443"}
    - {search: "%CLUSTERCIDR%", replace: "{{ CLUSTER_CIDR }}"}

- name: Deploy Kube Router
  shell: kubectl apply -f {{ temp_dir }}/generic-kuberouter-all-features.yaml

- name: Verify Kube Router daemons are running
  shell: kubectl get ds kube-router -n kube-system -o jsonpath='{.status.numberReady}'
  register: result
  until: (groups['workers'] | length) == (result.stdout | int)
  retries: 6
  delay: 5