---
- block:
    - name: Copy certs and configs to controller
      copy:
        src: "{{ WORK_DIR }}/{{ item }}"
        dest: "/var/lib/kubernetes"
      loop:
        - encryption-config.yaml
        - kubernetes-key.pem
        - kubernetes.pem

    - name: Create systemd unit for kube-apiserver
      template:
        src: "../templates/kube-apiserver.service.j2"
        dest: "/etc/systemd/system/kube-apiserver.service"
      vars:
        apiserver_count: "{{ groups['controllers'] | length }}"
        service_cidr: "{{ SERVICE_CIDR }}"
        etcd_servers_string: "{{
          groups['controllers'] |
          map('extract', hostvars , 'cluster_ip') |
          map('regex_replace', '(.+)' , 'https://\\1:2379') |
          list |
          join(',')
        }}"

    - name: Download kube-apiserver binary
      uri:
        url: "{{ K8S_RELEASE_BASE_URL }}/kube-apiserver"
        dest: /usr/local/bin/
        mode: "755"
        status_code: [200, 304]

    - name: Start {{ service_name }} server
      systemd:
        name: "kube-apiserver"
        state: restarted
        daemon_reload: yes
        enabled: yes
  become: yes
