---
- block:
    - name: Set template variables for {{ name }}
      set_fact:
        cn: "{{ cn }}"
        org: "{{ org }}"

    - name: Create CSR for {{ name }}
      template:
        src: ../templates/csr.json.j2
        dest: "{{ WORK_DIR }}/{{ name }}-csr.json"

    - name: Generate {{ name }} cert
      shell:
        cmd: >
          cfssl gencert
          -ca=ca.pem
          -ca-key=ca-key.pem
          -config=ca-config.json
          {% if hostname is defined %}
          -hostname={{ hostname }}
          {% endif %}
          -profile=kubernetes
          {{ name }}-csr.json | cfssljson -bare {{ name }}
        chdir: "{{ WORK_DIR }}"

  delegate_to: localhost