---
- name: Create CA config file
  copy:
    content: |
      {
        "signing": {
          "default": {
            "expiry": "8760h"
          },
          "profiles": {
            "kubernetes": {
              "usages": ["signing", "key encipherment", "server auth", "client auth"],
              "expiry": "8760h"
            }
          }
        }
      }
    dest: "{{ WORK_DIR }}/ca-config.json"

- name: Create CA CSR file
  template:
    src: ../templates/csr.json.j2
    dest: "{{ WORK_DIR }}/ca-csr.json"
  vars:
    cn: "Kubernetes"
    org: "Kubernetes"

- name: Provision CA
  shell:
    cmd: cfssl gencert -initca ca-csr.json | cfssljson -bare ca
    chdir: "{{ WORK_DIR }}"
