---
- name: Download {{ item.name }}
  uri:
    url: https://storage.googleapis.com/kubernetes-the-hard-way/cfssl/linux/{{ item.name }}
    dest: /usr/local/bin/
    mode: "755"
    status_code: [200, 304]
  become: yes

- name: Verify {{ item.name }} is executable
  shell: "{{ item.name }} {{ item.cmd }}"
  register: result

- fail:
    msg: "{{ item.name }} not executable"
  when: result.rc != 0