---
- hosts: directors
  connection: local
  tasks:
    - name: Configure kubectl for remote access
      shell:
        cmd: "kubectl config {{ item }}"
        chdir: "{{ WORK_DIR }}"
      loop:
        - "set-cluster kubernetes-the-hard-way
          --certificate-authority=ca.pem
          --embed-certs=true
          --server=https://{{ API_SERVER_IP }}:6443"
        - "set-credentials admin
          --client-certificate=admin.pem
          --client-key=admin-key.pem"
        - "set-context kubernetes-the-hard-way
          --cluster=kubernetes-the-hard-way
          --user=admin"
        - use-context kubernetes-the-hard-way

    - include_tasks: ../tasks/kube-router-install.yaml

    - name: Deploy DNS cluster add-on
      shell: kubectl apply -f https://storage.googleapis.com/kubernetes-the-hard-way/coredns.yaml
