---
- hosts: controllers
  vars:
    task_dir: "../tasks"
  tasks:
    - include_tasks: "{{ task_dir }}/kubeconfig-generate.yaml"
      loop:
        - {name: kube-controller-manager, kube_cfg_user: "system:kube-controller-manager"}
        - {name: kube-scheduler, kube_cfg_user: "system:kube-scheduler"}
        - {name: admin, kube_cfg_user: "admin"}

    - include_tasks: "{{ task_dir }}/encryption-generate.yaml"

    - name: Copy files to controller
      copy:
        src: "{{ WORK_DIR }}/{{ item }}"
        dest: "~/"
      loop:
        - ca.pem
        - ca-key.pem
        - kubernetes-key.pem
        - kubernetes.pem
        - service-account-key.pem
        - service-account.pem
        - admin.kubeconfig
        - kube-controller-manager.kubeconfig
        - kube-scheduler.kubeconfig
        - encryption-config.yaml
