---
- hosts: workers
  vars:
    tasks_dir: "../tasks"
  tasks:
    - include_tasks: "{{ tasks_dir }}/pki-generate-cert.yaml"
      loop:
        - name: "{{ inventory_hostname }}"
          cn: "system:node:{{ inventory_hostname }}"
          org: "system:nodes"
          hostname: "{{ inventory_hostname + ',' + cluster_ip }}"

    - include_tasks: "{{ tasks_dir }}/kubeconfig-generate.yaml"
      loop:
        - name: "{{ inventory_hostname }}"
          kube_cfg_user: "system:node:{{ inventory_hostname }}"

    - name: Copy files to worker
      copy:
        src: "{{ WORK_DIR }}/{{ item }}"
        dest: "~/"
      loop:
        - ca.pem
        - "{{ inventory_hostname }}-key.pem"
        - "{{ inventory_hostname }}.pem"
        - "{{ inventory_hostname }}.kubeconfig"
