---
- import_playbook: worker-generate-files.yaml

- hosts: workers
  tasks:
  - name: Copy certs and kubeconfig to worker
    copy:
      src: "{{ WORK_DIR }}/{{ item }}"
      dest: "~/"
    loop:
    - ca.pem
    - "{{ inventory_hostname }}-key.pem"
    - "{{ inventory_hostname }}.pem"
    - "{{ inventory_hostname }}.kubeconfig"
